### ISSUE TITLE
[enhancement] View Scene Capability

### ISSUE THREAD

**Issue by Eagle0600** [claypooj21/journals-like-a-script#2]
I would like to have the option to view a scene instead of activating it. There are a number of possible implementations and use cases.

Use cases include wanting to go to a scene without activating it during preparation time, dragging some but not all players to a scene, and allowing players to click links to go to a scene themselves.

The simplest would be to create an alternative tag: `@ViewScene` instead of `@ActivateScene`. Alternatively, players without scene activation permission could be allowed to view a scene. Alternatively, left and right click could have different functionality. Alternatively, various options could be chosen from settings configuration.

I would also appreciate it if scene activation links could be hidden from players who lack permission to use them.

**Comment by claypooj21** [comment]
### The short version

Hey @Eagle0600, thanks for the feedback! There's kind of an essay of crap after this, so I figured I'd just give you the short and sweet.

Based on your input, in the next update (v2.0.1):
* view scenes instead of activating them by `ctrl + left click`
* configuration option for non-GM users to view scenes instead of trying (and failing) to activate them
* configuration option for what non-GM users get to see from JLAS links (full link, only text, nothing)
* added text enricher that only views scenes and opens journal entries

The rest of this post is just some background. I should have v2.0.1 out sometime this week, but I need to sleep.

Thanks again for your input!

### View scene

Based on your input, in the next update (v2.0.1), JLAS links will allow you to view the scene and pull up the scene's journal entry if you hold `ctrl` and click. If you just click the scene, the default will still be to Activate the scene and pull up the scene's journal. I think this is a good option since typically the expected behavior of right-clicking is pulling up a context menu (which might be a future release; thanks for the idea!), whereas holding a key and clicking is often associated with an alternate function.

### Allow players to view a scene instead of activating it

I implemented:

> players without scene activation permission could be allowed to view a scene

However, some words of caution. I did some testing on the permissions side of things. The problem is, as of Foundry v10.290, the `scene.view()` function doesn't check user permissions at all, meaning that any authenticated user can *view* any scene at any point in time regardless of whether the scene shows up in the navigation. It seems that Foundry's *only* safeguard against users viewing whatever scene they want is to hide the buttons from players (out of site, out of mind). In other words, non-GM players would be able to view a scene using a JLAS link that they could not otherwise navigate to through the UI.

Unlike `scene.view()`, `scene.activate()` *does* check for "update" permission on the scene. In JLAS v2.0.0, even though players could potentially see the links in a shared journal, clicking the link gives them a permissions error generated by Foundry when `scene.activate()` is called by a non-GM user. If their ownership (permission) level for the scene's journal isn't at least "Limited", they will also see a warning (generated by JLAS) about not having permission to open the Journal Page associated with the scene.

Implementing a default behavior where JLAS falls back to allowing players to view scenes when the link is clicked also has high potential to cause problems for other users. Anyone who has already shared journals with their players and is expecting the link not to work for their players would be in for an unpleasant surprise as soon as they updated JLAS. So instead, I've added configuration options that allow you to choose what behavior you'd like, with the default being to display the link but deny non-GM users from following it.

Depending on you use case, I think a better solution may be to, as you said:

> create an alternative tag

So I've added that as well.

### Hide the activation links

Foundry has the built-in "Secret" format (Format>Block>Secret), which gives you control over which individual JLAS links get displayed. Its biggest downside is that it's a block format, and not an inline one.

I created a configuration option that allows you to control how functional a JLAS link is for non-GM users. Basically, it either:
*appears to everyone in exactly the same way (though unless you let users view links, they'll just get warnings, as stated above),
* it appears as only the text from the link, or
* it is removed entirely and replaced with a zero-width space (kind of hacky, but it works).

The downside to the configuration option is that it's global. It will affect all JLAS links the same, so if you need to be able to selectively hide and reveal links, I recommend using the "Secret" format for the time being.

**Comment by Eagle0600** [comment]
Thank you for the in-depth response.

**Comment by claypooj21** [comment]
No worries! I'm a couple days late, but JLAS v2.1.0 is released! Thanks for your input!
